primary/urls.py
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from django.http import Http404, HttpResponsePermanentRedirect
from django.urls import path, reverse
from django.utils.translation import gettext_lazy as _
from martor.views import markdown_search_user

from judge.feed import (AtomBlogFeed, AtomCommentFeed, AtomProblemFeed,
                        BlogFeed, CommentFeed, ProblemFeed)
from judge.sitemap import (BlogPostSitemap, HomePageSitemap,
                           OrganizationSitemap, ProblemSitemap,
                           SolutionSitemap, UrlSitemap, UserSitemap)
from judge.views import (TitledTemplateView, about, blog, comment, language,
                         license, mailgun, organization, preview, problem,
                         problem_manage, register, stats, status, submission,
                         tasks, ticket, user, widgets)
from judge.views.problem_data import (ProblemDataView, ProblemSubmissionDiff,
                                      problem_data_file, problem_init_view)
from judge.views.register import RegistrationView
from judge.views.select2 import (  # , UserSearchSematicView
    AssigneeSelect2View, CommentSelect2View, OrganizationSelect2View,
    ProblemSelect2View, TicketUserSelect2View, UserSearchSelect2View,
    UserSelect2View)
from judge.views.widgets import martor_image_uploader

admin.autodiscover()

register_patterns = [
    path('login/', user.CustomLoginView.as_view(), name='auth_login'),
    path('logout/', user.UserLogoutView.as_view(), name='auth_logout'),
    path('password/change/', user.CustomPasswordChangeView.as_view(), name='password_change'),
    path('password/change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='registration/password_change_done.html',
    ), name='password_change_done'),
    path('password/reset/', auth_views.PasswordResetView.as_view(
        template_name='registration/password_reset.html',
        html_email_template_name='registration/password_reset_email.html',
        email_template_name='registration/password_reset_email.txt',
    ), name='password_reset'),
    path('password/reset/confirm/<uuid:uidb64>-<slug:token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='registration/password_reset_confirm.html',
        ), name='password_reset_confirm'),
    path('password/reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html',
    ), name='password_reset_complete'),
    path('password/reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html',
    ), name='password_reset_done'),
    path('social/error/', register.social_auth_error, name='social_auth_error'),
]

if getattr(settings, 'OPEN_PUBLIC_REGISTER', True):
    register_patterns += [
        path('activate/complete/',
            TitledTemplateView.as_view(template_name='registration/activation_complete.html',
                                    title='Activation Successful!'),
            name='registration_activation_complete'),
        # Activation keys get matched by \w+ instead of the more specific
        # [a-fA-F0-9]{40} because a bad activation key should still get to the view;
        # that way it can return a sensible "invalid key" message instead of a
        # confusing 404.
        # path('activate/<slug:activation_key>/',
        #     ActivationView.as_view(title='Activation key invalid'),
        #     name='registration_activate'),
        path('register/',
            RegistrationView.as_view(title='Register'),
            name='registration_register'),
        path('register/complete/',
            TitledTemplateView.as_view(template_name='registration/registration_complete.html',
                                    title='Registration Completed'),
            name='registration_complete'),
        path('register/closed/',
            TitledTemplateView.as_view(template_name='registration/registration_closed.html',
                                    title='Registration not allowed'),
            name='registration_disallowed'),
    ]


def exception(request):
    if not request.user.is_superuser:
        raise Http404()
    raise RuntimeError('@Xyene asked me to cause this')


def paged_list_view(view, name):
    return include([
        path('', view.as_view(), name=name),
        path('<int:page>', view.as_view(), name=name),
    ])


urlpatterns = [
    # path('', blog.IndexView.as_view()),
    path('grappelli/', include('grappelli.urls')),
    path('docs/', include('grappelli.urls_docs')),
    path('', blog.PostList.as_view(template_name='home.html', title=_('Home')), kwargs={'page': 1}, name='home'),
    path('500/', exception),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('accounts/', include(register_patterns)),
    path('', include('social_django.urls')),
    
    # Create many users
    path('manyuser/', user.CreateManyUser.as_view(), name="many_user"),
    path('createuser/', include([
        path('csv/', user.CreateCSVUser.as_view(), name='create_user_csv'),
        path('confirm/', user.ConfirmCSVUser.as_view(), name='create_user_confirm'),
        path('success/', user.SuccessCSVUser.as_view(), name='success_csv_user'),
    ])),

    path('problems/', problem.ProblemList.as_view(), name='problem_list'),
    path('problems/random/', problem.RandomProblem.as_view(), name='problem_random'),
	# path('problems/new/', problem.ProblemNew.as_view(), name='problem_new'),

    path('problem/<slug:problem>', include([
        # path('/update', problem.ProblemEdit.as_view(), name='problem_edit'),
        path('', problem.ProblemDetail.as_view(), name='problem_detail'),
        path('/ps', problem.PublicSolutionCreateView.as_view(), name='create_public_solution'),
        path('/listps', problem.PublicSolutionListView.as_view(), name='public_solution'),
        path('/public_solution/<int:pk>', problem.PublicSolutionDetailView.as_view(), name='public_solution_detail'),
        path('/editorial', problem.ProblemSolution.as_view(), name='problem_editorial'),
        path('/raw', problem.ProblemRaw.as_view(), name='problem_raw'),
        path('/pdf', problem.ProblemPdfView.as_view(), name='problem_pdf'),
        path('/pdf/<slug:language>', problem.ProblemPdfView.as_view(), name='problem_pdf'),
        path('/clone', problem.ProblemClone.as_view(), name='problem_clone'),
        path('/submit', problem.ProblemSubmit.as_view(), name='problem_submit'),
        path('/resubmit/<slug:submission>', problem.ProblemSubmit.as_view(), name='problem_submit'),

        path('/rank/', paged_list_view(submission.RankedSubmissions, 'ranked_submissions')),
        path('/submissions/', paged_list_view(submission.ProblemSubmissions, 'chronological_submissions')),
        path('/submissions/<str:user>/', paged_list_view(submission.UserProblemSubmissions, 'user_submissions')),

        path('/', lambda _, problem: HttpResponsePermanentRedirect(reverse('problem_detail', args=[problem]))),

        path('/test_data', ProblemDataView.as_view(), name='problem_data'),
        path('/test_data/init', problem_init_view, name='problem_data_init'),
        path('/test_data/diff', ProblemSubmissionDiff.as_view(), name='problem_submission_diff'),
        path('/data/<str:path>', problem_data_file, name='problem_data_file'),

        path('/tickets', ticket.ProblemTicketListView.as_view(), name='problem_ticket_list'),
        path('/tickets/new', ticket.NewProblemTicketView.as_view(), name='new_problem_ticket'),

        path('/manage/submission', include([
            path('', problem_manage.ManageProblemSubmissionView.as_view(), name='problem_manage_submissions'),
            path('/rejudge', problem_manage.RejudgeSubmissionsView.as_view(), name='problem_submissions_rejudge'),
            path('/rejudge/preview', problem_manage.PreviewRejudgeSubmissionsView.as_view(),
                name='problem_submissions_rejudge_preview'),
            path('/rejudge/success/<slug:task_id>', problem_manage.rejudge_success,
                name='problem_submissions_rejudge_success'),
            path('/rescore/all', problem_manage.RescoreAllSubmissionsView.as_view(),
                name='problem_submissions_rescore_all'),
            path('/rescore/success/<slug:task_id>', problem_manage.rescore_success,
                name='problem_submissions_rescore_success'),
        ])),
    ])),
    path('publicsolution/upvote/', problem.upvote_solution, name='solution_upvote'),
    path('publicsolution/downvote/', problem.downvote_solution, name='solution_downvote'),

    path('submissions/', paged_list_view(submission.AllSubmissions, 'all_submissions')),
    path('submissions/user/<str:user>/', paged_list_view(submission.AllUserSubmissions, 'all_user_submissions')),

    path('src/<slug:submission>', submission.SubmissionSource.as_view(), name='submission_source'),
    path('src/<slug:submission>/raw', submission.SubmissionSourceRaw.as_view(), name='submission_source_raw'),

    path('submission/<slug:submission>', include([
        path('', submission.SubmissionStatus.as_view(), name='submission_status'),
        path('/abort', submission.abort_submission, name='submission_abort'),
    ])),

    path('users/', include([
        path('', user.users, name='user_list'),
        path('<slug:page>', lambda request, page:
            HttpResponsePermanentRedirect('%s?page=%s' % (reverse('user_list'), page))),
        path('find', user.user_ranking_redirect, name='user_ranking_redirect'),
    ])),

    path('user', user.UserAboutPage.as_view(), name='user_page'),
    path('edit/<str:user>/', user.EditProfile.as_view(), name='user_edit_profile'),

judge/models/ticket.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.utils.translation import gettext_lazy as _

from judge.models.profile import Profile


class Ticket(models.Model):
    title = models.CharField(max_length=100, verbose_name=_('ticket title'))
    user = models.ForeignKey(Profile, verbose_name=_('ticket creator'), related_name='tickets',
                             on_delete=models.CASCADE)
    time = models.DateTimeField(verbose_name=_('creation time'), auto_now_add=True)
    assignees = models.ManyToManyField(Profile, verbose_name=_('assignees'), related_name='assigned_tickets',
                                       blank=True)
    notes = models.TextField(verbose_name=_('quick notes'), blank=True,
                             help_text=_('Staff notes for this issue to aid in processing.'))
    content_type = models.ForeignKey(ContentType, verbose_name=_('linked item type'),
                                     on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField(verbose_name=_('linked item ID'))
    linked_item = GenericForeignKey()
    is_open = models.BooleanField(verbose_name=_('is ticket open?'), default=True)


class TicketMessage(models.Model):
    ticket = models.ForeignKey(Ticket, verbose_name=_('ticket'), related_name='messages',
                               related_query_name='message', on_delete=models.CASCADE)
    user = models.ForeignKey(Profile, verbose_name=_('poster'), related_name='ticket_messages',
                             on_delete=models.CASCADE)
    body = models.TextField(verbose_name=_('message body'))
    time = models.DateTimeField(verbose_name=_('message time'), auto_now_add=True)

judge/views/preview.py
from django.http import HttpResponseBadRequest
from django.views.generic.base import ContextMixin, TemplateResponseMixin, View


class MarkdownPreviewView(TemplateResponseMixin, ContextMixin, View):
    def post(self, request, *args, **kwargs):
        try:
            self.preview_data = data = request.POST['content']
        except KeyError:
            return HttpResponseBadRequest('No preview data specified.')

        return self.render_to_response(self.get_context_data(
            preview_data=data,
        ))


class ProblemMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'problem/preview.html'


class BlogMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'blog/preview.html'


class ContestMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'contest/preview.html'


class CommentMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'comments/preview.html'


class FlatPageMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'flatpage-preview.html'


class ProfileMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'user/preview.html'


class OrganizationMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'organization/preview.html'


class SolutionMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'solution-preview.html'


class LicenseMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'license-preview.html'


class TicketMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'ticket/preview.html'


class DefaultMarkdownPreviewView(MarkdownPreviewView):
    template_name = 'default-preview.html'

templates/ticket/edit-notes.html
<form id="edit-notes" action="{{ url('ticket_notes', ticket.id) }}" method="post">
    {% csrf_token %}
    {{ form.notes }}
    <button type="submit" class="ui primary button">{{ _('Update') }}</button>
</form>

templates/ticket/message.html
<section id="message-{{ message.id }}" class="message">
    <div class="info">
        <a href="{{ url('user_page', message.user.username) }}" class="user">
            <img src="{{ gravatar(message.user, 135) }}" class="gravatar">
            <div class="username {{ message.user.css_class }}">{{ message.user.username }}</div>
        </a>
    </div>
    <div class="detail">
        <div class="header">
            <div class="relative-time"></div>
            <div class="message-date">{{ message.time|date('DATE_FORMAT') }}</div>
            <div class="message-time">{{ message.time|time('TIME_FORMAT') }}</div>
        </div>
        <div class="content content-description">
            {{ message.body|markdown('ticket')|reference|str|safe }}
        </div>
    </div>
</section>

templates/ticket/new.html
{% extends "base.html" %}

{% block media %}
    {{ form.media.css }}
    <style>
        form#ticket-form {
            display: block;
            margin: 0 auto;
            width: 100%;
            max-width: 750px;
            padding-top: 1em;
        }

        #id_title {
            width: 100%;
        }

        form#ticket-form .submit {
            margin: 10px 0 0 auto;
        }
    </style>
{% endblock %}

{% block js_media %}{{ form.media.js }}{% endblock %}

{% block body %}
    <form id="ticket-form" action="" method="POST" class="form-area">
        {% block guideline_message %}{% endblock %}
        {% csrf_token %}
        <div class="title-block{% if form.title.errors %} error{% endif %}">{{ form.title }}</div>
        {% if form.errors %}
            <div class="form-errors">
                {{ form.non_field_errors() }}
                {{ form.title.errors }}
                {{ form.body.errors }}
            </div>
        {% endif %}
        <div class="body-block">{{ form.body }}</div>
        <button type="submit" class="ui primary button">{{ _('Create') }}</button>
    </form>
{% endblock %}

templates/ticket/new_problem.html
{% extends "ticket/new.html" %}

{% block guideline_message %}
    {% if not request.in_contest %}
        <div class="alert alert-warning alert-dismissable">
            <a class="close">x</a>
            <b>{{ _('Thanks for opening a ticket!') }}</b>
            <br><br>
            {{ _('Please keep in mind that this form is for reporting issues with a problem statement, and not for asking for help. If you require assistance on solving a problem, ask in the comments instead.') }}
        </div>
    {% endif %}
{% endblock %}

templates/ticket/preview.html
{{ preview_data|markdown('ticket')|reference|str|safe }}
{% if REQUIRE_JAX %}
    <div data-config="{{ static('mathjax_config.js') }}" class="require-mathjax-support"></div>
{% endif %}

templates/ticket/row.html
<tr id="ticket-{{ ticket.id }}">
    <td><i class="fa {% if ticket.is_open %}fa-exclamation-circle{% else %}fa-check-circle-o{% endif %}"></i></td>
    <td>{{ ticket.id }}</td>
    <td><a href="{{ url('ticket', ticket.id) }}">{{ ticket.title }}</a></td>
    <td>{{ link_user(ticket.user) }}</td>
    <td>{{ link_users(ticket.assignees.all()) }}</td>
</tr>

templates/ticket/ticket.html
{% extends "base.html" %}
{% block media %}
    {{ form.media.css }}
    <style>
        #content > h2:first-child small {
            color: #999;
            font-size: 0.9em;
            margin-left: 0.3em;
        }

        #content > h2:first-child .status, #content > h2:first-child .title {
            display: inline;
        }

        #content > h2:first-child .fa-check-circle-o {
            color: #00a900;
        }

        #content > h2:first-child .fa-exclamation-circle {
            color: darkred;
        }

        .container {
            width: 100%;
            margin: 0 auto;
            display: flex;
            flex-direction: row;
            flex-wrap: wrap-reverse;
            max-width: 1000px;
        }

        .ticket-sidebar {
            flex: 1;
            padding: 10px 0 0 10px;
            min-width: 150px;
            max-width: 200px;
        }

        .ticket-info {
            position: sticky;
            top: 60px;
        }

        .ticket-messages {
            flex: 1;
        }

        .info-box {
            margin: 5px 0 10px;
            border: 1px #999 solid;
            border-radius: 5px;
        }

        .info-title {
            padding: 2px 5px;
            font-weight: 600;
            border-bottom: 1px #999 solid;
            background: #eee;
            border-radius: 5px 5px 0 0;
        }

        .info-data {
            padding: 2px 5px;
        }

        .info-empty {
            color: #999;
            font-style: italic;
        }

        .close-ticket {
            display: block;
            width: 100%;
            background: linear-gradient(to bottom, #4bad00 0%, #278811 100%);
            border-color: #24710e;
            font-weight: 600;
        }

        .close-ticket:hover {
            background: #24710e;
        }

        .open-ticket {
            display: block;
            width: 100%;
            background: linear-gradient(to bottom, #ff130f, #b03d17);
            border-color: #853011;
            font-weight: 600;
        }

        .open-ticket:hover {
            background: #853011;
        }

        a.edit-notes {
            float: right;
        }

        #ticket-notes .info-real :first-child {
            margin-top: 0;
        }

        #ticket-notes .info-real :last-child {
            margin-bottom: 0;
        }

        .message {
            display: flex;
            padding-top: 15px;
        }

        .message .info {
            width: 130px;
        }

        .message .username {
            text-align: center;
        }

        .message .gravatar {
            width: 80px;
            display: block;
            margin: 0 auto;
        }

        .message .message-date, .message .message-time {
            display: inline-block;
        }

        .message .detail {
            border: 1px #999 solid;
            border-radius: 5px;
            flex: 1;
            min-width: 200px;
        }

        .message .header {
            background: #eee;
            color: #777;
            border-bottom: 1px solid #999;
            border-radius: 5px 5px 0 0;
            padding: 2px 7px;
            text-align: right;
        }

        .message .content {
            padding: 7px;
        }

        .message .content :first-child {
            margin-top: 0;
        }

        .message .content :last-child {
            margin-bottom: 0;
        }

        .new-message .detail {
            padding: 8px 10px;
        }

        .new-message .submit, #edit-notes .submit {
            margin: 10px 0 0 auto;
        }
    </style>
{% endblock %}

{% block js_media %}
    {{ form.media.js }}
    <script src="{{ static('libs/featherlight/featherlight.min.js') }}" type="text/javascript"></script>
    <script type="text/javascript" src="{{ static('event.js') }}?1"></script>
    <script type="text/javascript">
        $(function () {
            var $h2 = $('#content').find('> h2:first-child');
            var $status = $h2.find('.status i'), $title = $h2.find('.title');

            function update_ticket_state(open) {
                if (open)
                    $status.removeClass('fa-check-circle-o').addClass('fa-exclamation-circle');
                else
                    $status.removeClass('fa-exclamation-circle').addClass('fa-check-circle-o');
                $('.close-ticket').toggle(open);
                $('.open-ticket').toggle(!open);
            }

            $('.close-ticket, .open-ticket').click(function () {
                var open = $(this).attr('data-open') == '1';
                $.ajax({
                    url: $(this).attr('data-ajax'), type: 'POST',
                    success: function () {
                        update_ticket_state(open);
                    },
                    error: function (data) {
                        alert('Could not change ticket: ' + data.responseText);
                    }
                });
            });

            $('.edit-notes').featherlight({
                afterOpen: function () {
                    var $form = $('#edit-notes');
                    $form.find('.submit').click(function () {
                        $.post($form.attr('action'), $form.serialize()).done(function (data) {
                            $('#ticket-notes').find('.info-empty').toggle(!data).end().find('.info-real').html(data);
                            $.featherlight.current().close();
                        });
                        return false;
                    });
                }
            });

            var page_ref_key = 'ticket:open:{{ ticket.id }}', page_close_key = page_ref_key + ':close';
            var page_ref;

            function increase_page_ref() {
                if (page_ref_key in localStorage)
                    localStorage[page_ref_key] = page_ref = +localStorage[page_ref_key] + 1;
                else
                    localStorage[page_ref_key] = page_ref = 1;
            }

            function decrease_page_ref() {
                if (page_ref_key in localStorage) {
                    localStorage[page_close_key] = page_ref;
                    delete localStorage[page_close_key];
                    localStorage[page_ref_key] = +localStorage[page_ref_key] - 1;
                }
                page_ref = null;
            }

            function is_highest_ref() {
                console.log(localStorage[page_ref_key], page_ref);
                if (page_ref_key in localStorage)
                    return +localStorage[page_ref_key] == page_ref;
                return true;
            }

            $(window).on('storage', function (e) {
                e = e.originalEvent;
                if (e.key == page_close_key && e.newValue !== null)
                    if (page_ref != null && page_ref > +e.newValue)
                        --page_ref;
            });

            register_notify('ticket', {
                change: function (enabled) {
                    if (enabled)
                        increase_page_ref();
                }
            });

            $(window).on('beforeunload', function () {
                decrease_page_ref();
            });

            function ticket_status(ticket) {
                update_ticket_state(ticket.open);
                if (is_highest_ref())
                    notify('ticket', (ticket.open ? '{{ _('Reopened: ') }}' :
                        '{{ _('Closed: ') }}') + $title.text());
            }

            function ticket_message(ticket) {
                console.log('Fetching data for: ' + ticket.message);
                $.ajax({
                    url: '{{ url('ticket_message_ajax', ticket.id) }}',
                    data: {message: ticket.message},
                    success: function (data) {
                        console.log('Got data for: ' + ticket.message);
                        console.log(data);
                        $('#messages').append($(data.message));
                    },
                    error: function (data) {
                        if (data.status === 403)
                            console.log('No right to see: ' + ticket.message);
                        else {
                            console.log('Could not load ticket message:');
                            console.log(data.responseText);
                        }
                    }
                });
            }

            window.load_dynamic_update = function () {
                event_dispatcher.on('ticket-{{ ticket.id }}', function (message) {
                    console.log(message);
                    switch (message.type) {
                        case 'ticket-status':
                            ticket_status(message);
                            break;
                        case 'ticket-message':
                            ticket_message(message);
                            break;
                    }
                });
            }
        });
    </script>

    {% if EVENT_LAST_MSG %}
        <script type="text/javascript">
            $(function () {
                load_dynamic_update();
            });
        </script>
    {% endif %}
{% endblock %}

{% block content_title %}
    <div class="status">
        <i class="fa {% if ticket.is_open %}fa-exclamation-circle{% else %}fa-check-circle-o{% endif %}"></i>
    </div>
    <div class="title">{{ ticket.title }}</div><small>#{{ ticket.id }}</small>
{% endblock %}

{% block body %}
    <div class="container">
        <div class="ticket-messages">
            <main id="messages">
                {% for message in ticket_messages %}
                    {% include "ticket/message.html" %}
                {% endfor %}
            </main>
            <hr>
            <section class="message new-message">
                <div class="info">
                    <a href="{{ url('user_page', request.user.username) }}" class="user">
                        <img src="{{ gravatar(request.user, 135) }}" class="gravatar">
                        <div class="username {{ request.user.css_class }}">{{ request.user.username }}</div>
                    </a>
                </div>
                <div class="detail">
                    <form action="" method="post">
                        {% csrf_token %}
                        {% if form.non_field_errors() or form.body.errors %}
                            <div class="form-errors">
                                {{ form.non_field_errors() }}
                                {{ form.body.errors }}
                            </div>
                        {% endif %}
                        <div class="body-block">{{ form.body }}</div>
                        <button type="submit" class="ui primary button">{{ _('Post') }}</button>
                    </form>
                </div>
            </section>
        </div>
        <aside class="ticket-sidebar">
            <div class="ticket-info">
                <div class="info-box">
                    <div class="info-title">{{ _('Associated object') }}</div>
                    <div class="info-data">
                        <a href="{{ ticket.linked_item.get_absolute_url() }}">{{ ticket.linked_item }}</a>
                    </div>
                </div>
                <div class="info-box">
                    <div class="info-title">
                        {% trans trimmed count=assignees|length %}
                            Assignee
                        {% pluralize %}
                            Assignees
                        {% endtrans %}
                    </div>
                    <div class="info-data">
                        {% if assignees %}
                            {{ link_users(assignees) }}
                        {% else %}
                            <div class="info-empty">{{ _('No one is assigned.') }}</div>
                        {% endif %}
                    </div>
                </div>

                <button data-ajax="{{ url('ticket_close', ticket.id) }}" data-open="0" class="ui fluid negative button close-ticket"
                        {% if not ticket.is_open %}style="display: none"{% endif %}>{{ _('Close ticket') }}</button>
                <button data-ajax="{{ url('ticket_open', ticket.id) }}" data-open="1" class="ui fluid positive button open-ticket"
                        {% if ticket.is_open %}style="display: none"{% endif %}>{{ _('Reopen ticket') }}</button>

                {% if perms.judge.change_ticket or request.user in assignees %}
                    <div class="info-box">
                        <div class="info-title">{{ _('Assignee notes') }}
                            <a href="#" data-featherlight="{{ url('ticket_notes', ticket.id) }}" class="edit-notes">
                                <i class="fa fa-pencil"></i>
                            </a>
                        </div>
                        <div id="ticket-notes" class="info-data">
                            <div{% if ticket.notes %} style="display: none"{% endif %} class="info-empty">
                                {{ _('Nothing here.') }}
                            </div>
                            <div class="info-real">{{ ticket.notes|linebreaks }}</div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </aside>
    </div>
{% endblock %}