primary/urls.py
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from django.http import Http404, HttpResponsePermanentRedirect
from django.urls import path, reverse
from django.utils.translation import gettext_lazy as _
from martor.views import markdown_search_user

from judge.feed import (AtomBlogFeed, AtomCommentFeed, AtomProblemFeed,
                        BlogFeed, CommentFeed, ProblemFeed)
from judge.sitemap import (BlogPostSitemap, HomePageSitemap,
                           OrganizationSitemap, ProblemSitemap,
                           SolutionSitemap, UrlSitemap, UserSitemap)
from judge.views import (TitledTemplateView, about, blog, comment, language,
                         license, mailgun, organization, preview, problem,
                         problem_manage, register, stats, status, submission,
                         tasks, ticket, user, widgets)
from judge.views.problem_data import (ProblemDataView, ProblemSubmissionDiff,
                                      problem_data_file, problem_init_view)
from judge.views.register import RegistrationView
from judge.views.select2 import (  # , UserSearchSematicView
    AssigneeSelect2View, CommentSelect2View, OrganizationSelect2View,
    ProblemSelect2View, TicketUserSelect2View, UserSearchSelect2View,
    UserSelect2View)
from judge.views.widgets import martor_image_uploader

admin.autodiscover()

register_patterns = [
    path('login/', user.CustomLoginView.as_view(), name='auth_login'),
    path('logout/', user.UserLogoutView.as_view(), name='auth_logout'),
    path('password/change/', user.CustomPasswordChangeView.as_view(), name='password_change'),
    path('password/change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='registration/password_change_done.html',
    ), name='password_change_done'),
    path('password/reset/', auth_views.PasswordResetView.as_view(
        template_name='registration/password_reset.html',
        html_email_template_name='registration/password_reset_email.html',
        email_template_name='registration/password_reset_email.txt',
    ), name='password_reset'),
    path('password/reset/confirm/<uuid:uidb64>-<slug:token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='registration/password_reset_confirm.html',
        ), name='password_reset_confirm'),
    path('password/reset/complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html',
    ), name='password_reset_complete'),
    path('password/reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html',
    ), name='password_reset_done'),
    path('social/error/', register.social_auth_error, name='social_auth_error'),
]

if getattr(settings, 'OPEN_PUBLIC_REGISTER', True):
    register_patterns += [
        path('activate/complete/',
            TitledTemplateView.as_view(template_name='registration/activation_complete.html',
                                    title='Activation Successful!'),
            name='registration_activation_complete'),
        # Activation keys get matched by \w+ instead of the more specific
        # [a-fA-F0-9]{40} because a bad activation key should still get to the view;
        # that way it can return a sensible "invalid key" message instead of a
        # confusing 404.
        # path('activate/<slug:activation_key>/',
        #     ActivationView.as_view(title='Activation key invalid'),
        #     name='registration_activate'),
        path('register/',
            RegistrationView.as_view(title='Register'),
            name='registration_register'),
        path('register/complete/',
            TitledTemplateView.as_view(template_name='registration/registration_complete.html',
                                    title='Registration Completed'),
            name='registration_complete'),
        path('register/closed/',
            TitledTemplateView.as_view(template_name='registration/registration_closed.html',
                                    title='Registration not allowed'),
            name='registration_disallowed'),
    ]


def exception(request):
    if not request.user.is_superuser:
        raise Http404()
    raise RuntimeError('@Xyene asked me to cause this')


def paged_list_view(view, name):
    return include([
        path('', view.as_view(), name=name),
        path('<int:page>', view.as_view(), name=name),
    ])


urlpatterns = [
    # path('', blog.IndexView.as_view()),
    path('grappelli/', include('grappelli.urls')),
    path('docs/', include('grappelli.urls_docs')),
    path('', blog.PostList.as_view(template_name='home.html', title=_('Home')), kwargs={'page': 1}, name='home'),
    path('500/', exception),
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('accounts/', include(register_patterns)),
    path('', include('social_django.urls')),
    
    # Create many users
    path('manyuser/', user.CreateManyUser.as_view(), name="many_user"),
    path('createuser/', include([
        path('csv/', user.CreateCSVUser.as_view(), name='create_user_csv'),
        path('confirm/', user.ConfirmCSVUser.as_view(), name='create_user_confirm'),
        path('success/', user.SuccessCSVUser.as_view(), name='success_csv_user'),
    ])),

    path('problems/', problem.ProblemList.as_view(), name='problem_list'),
    path('problems/random/', problem.RandomProblem.as_view(), name='problem_random'),
	# path('problems/new/', problem.ProblemNew.as_view(), name='problem_new'),

    path('problem/<slug:problem>', include([
        # path('/update', problem.ProblemEdit.as_view(), name='problem_edit'),
        path('', problem.ProblemDetail.as_view(), name='problem_detail'),
        path('/ps', problem.PublicSolutionCreateView.as_view(), name='create_public_solution'),
        path('/listps', problem.PublicSolutionListView.as_view(), name='public_solution'),
        path('/public_solution/<int:pk>', problem.PublicSolutionDetailView.as_view(), name='public_solution_detail'),
        path('/editorial', problem.ProblemSolution.as_view(), name='problem_editorial'),
        path('/raw', problem.ProblemRaw.as_view(), name='problem_raw'),
        path('/pdf', problem.ProblemPdfView.as_view(), name='problem_pdf'),
        path('/pdf/<slug:language>', problem.ProblemPdfView.as_view(), name='problem_pdf'),
        path('/clone', problem.ProblemClone.as_view(), name='problem_clone'),
        path('/submit', problem.ProblemSubmit.as_view(), name='problem_submit'),
        path('/resubmit/<slug:submission>', problem.ProblemSubmit.as_view(), name='problem_submit'),

        path('/rank/', paged_list_view(submission.RankedSubmissions, 'ranked_submissions')),
        path('/submissions/', paged_list_view(submission.ProblemSubmissions, 'chronological_submissions')),
        path('/submissions/<str:user>/', paged_list_view(submission.UserProblemSubmissions, 'user_submissions')),

        path('/', lambda _, problem: HttpResponsePermanentRedirect(reverse('problem_detail', args=[problem]))),

        path('/test_data', ProblemDataView.as_view(), name='problem_data'),
        path('/test_data/init', problem_init_view, name='problem_data_init'),
        path('/test_data/diff', ProblemSubmissionDiff.as_view(), name='problem_submission_diff'),
        path('/data/<str:path>', problem_data_file, name='problem_data_file'),

        path('/tickets', ticket.ProblemTicketListView.as_view(), name='problem_ticket_list'),
        path('/tickets/new', ticket.NewProblemTicketView.as_view(), name='new_problem_ticket'),

        path('/manage/submission', include([
            path('', problem_manage.ManageProblemSubmissionView.as_view(), name='problem_manage_submissions'),
            path('/rejudge', problem_manage.RejudgeSubmissionsView.as_view(), name='problem_submissions_rejudge'),
            path('/rejudge/preview', problem_manage.PreviewRejudgeSubmissionsView.as_view(),
                name='problem_submissions_rejudge_preview'),
            path('/rejudge/success/<slug:task_id>', problem_manage.rejudge_success,
                name='problem_submissions_rejudge_success'),
            path('/rescore/all', problem_manage.RescoreAllSubmissionsView.as_view(),
                name='problem_submissions_rescore_all'),
            path('/rescore/success/<slug:task_id>', problem_manage.rescore_success,
                name='problem_submissions_rescore_success'),
        ])),
    ])),
    path('publicsolution/upvote/', problem.upvote_solution, name='solution_upvote'),
    path('publicsolution/downvote/', problem.downvote_solution, name='solution_downvote'),

    path('submissions/', paged_list_view(submission.AllSubmissions, 'all_submissions')),
    path('submissions/user/<str:user>/', paged_list_view(submission.AllUserSubmissions, 'all_user_submissions')),

    path('src/<slug:submission>', submission.SubmissionSource.as_view(), name='submission_source'),
    path('src/<slug:submission>/raw', submission.SubmissionSourceRaw.as_view(), name='submission_source_raw'),

    path('submission/<slug:submission>', include([
        path('', submission.SubmissionStatus.as_view(), name='submission_status'),
        path('/abort', submission.abort_submission, name='submission_abort'),
    ])),

    path('users/', include([
        path('', user.users, name='user_list'),
        path('<slug:page>', lambda request, page:
            HttpResponsePermanentRedirect('%s?page=%s' % (reverse('user_list'), page))),
        path('find', user.user_ranking_redirect, name='user_ranking_redirect'),
    ])),

    path('user', user.UserAboutPage.as_view(), name='user_page'),
    path('edit/<str:user>/', user.EditProfile.as_view(), name='user_edit_profile'),

judge/models/comment.py
import itertools

from django.contrib.contenttypes.fields import GenericRelation
from django.core.cache import cache
from django.core.exceptions import ObjectDoesNotExist
from django.core.validators import RegexValidator
from django.db import models
from django.db.models import CASCADE
from django.urls import reverse
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel
from reversion.models import Version

from judge.models.interface import BlogPost
from judge.models.problem import Problem, Solution
from judge.models.profile import Profile
from judge.utils.cachedict import CacheDict

__all__ = ['Comment', 'CommentLock', 'CommentVote']

comment_validator = RegexValidator(r'^[pcs]:[a-z0-9]+$|^b:\d+$',
                                   _(r'Page code must be ^[pcs]:[a-z0-9]+$|^b:\d+$'))


class VersionRelation(GenericRelation):
    def __init__(self):
        super(VersionRelation, self).__init__(Version, object_id_field='object_id')

    def get_extra_restriction(self, alias, remote_alias):
        cond = super(VersionRelation, self).get_extra_restriction(alias, remote_alias)
        field = self.remote_field.model._meta.get_field('db')
        lookup = field.get_lookup('exact')(field.get_col(remote_alias), 'default')
        cond.add(lookup, 'AND')
        return cond


class Comment(MPTTModel):
    author = models.ForeignKey(Profile, verbose_name=_('commenter'), on_delete=CASCADE)
    time = models.DateTimeField(verbose_name=_('posted time'), auto_now_add=True)
    page = models.CharField(max_length=30, verbose_name=_('associated page'), db_index=True,
                            validators=[comment_validator])
    score = models.IntegerField(verbose_name=_('votes'), default=0)
    body = models.TextField(verbose_name=_('body of comment'), max_length=8192)
    hidden = models.BooleanField(verbose_name=_('hide the comment'), default=0)
    parent = TreeForeignKey('self', verbose_name=_('parent'), null=True, blank=True, related_name='replies',
                            on_delete=CASCADE)
    versions = VersionRelation()

    class Meta:
        verbose_name = _('comment')
        verbose_name_plural = _('comments')

    class MPTTMeta:
        order_insertion_by = ['-time']

    @classmethod
    def most_recent(cls, user, n, batch=None):
        queryset = cls.objects.filter(hidden=False) \
            .defer('author__about', 'body').order_by('-id')

        problem_cache = CacheDict(lambda code: Problem.objects.defer('description', 'summary').get(code=code))
        solution_cache = CacheDict(lambda code: Solution.objects.defer('content').get(problem__code=code))
        blog_cache = CacheDict(lambda id: BlogPost.objects.defer('summary', 'content').get(id=id))

        problem_access = CacheDict(lambda code: problem_cache[code].is_accessible_by(user))
        solution_access = CacheDict(lambda code: problem_access[code] and solution_cache[code].is_accessible_by(user))
        blog_access = CacheDict(lambda id: blog_cache[id].can_see(user))

        if batch is None:
            batch = 2 * n
        output = []
        for i in itertools.count(0):
            slice = queryset[i * batch:i * batch + batch]
            if not slice:
                break
            for comment in slice:
                page_key = comment.page[2:]
                try:
                    if comment.page.startswith('p:'):
                        has_access = problem_access[page_key]
                        comment.page_title = problem_cache[page_key].name
                    elif comment.page.startswith('s:'):
                        has_access = solution_access[page_key]
                        comment.page_title = _('Editorial for %s') % problem_cache[page_key].name
                    elif comment.page.startswith('b:'):
                        has_access = blog_access[page_key]
                        comment.page_title = blog_cache[page_key].title
                    else:
                        has_access = True
                except ObjectDoesNotExist:
                    pass
                else:
                    if has_access:
                        output.append(comment)
                if len(output) >= n:
                    return output
        return output

    @cached_property
    def link(self):
        try:
            link = None
            if self.page.startswith('p:'):
                link = reverse('problem_detail', args=(self.page[2:],))
            elif self.page.startswith('b:'):
                key = 'blog_slug:%s' % self.page[2:]
                slug = cache.get(key)
                if slug is None:
                    try:
                        slug = BlogPost.objects.get(id=self.page[2:]).slug
                    except ObjectDoesNotExist:
                        slug = ''
                    cache.set(key, slug, 3600)
                link = reverse('blog_post', args=(self.page[2:], slug))
            elif self.page.startswith('s:'):
                link = reverse('problem_editorial', args=(self.page[2:],))
        except Exception:
            link = 'invalid'
        return link

    @classmethod
    def get_page_title(cls, page):
        try:
            if page.startswith('p:'):
                return Problem.objects.values_list('name', flat=True).get(code=page[2:])
            elif page.startswith('b:'):
                return BlogPost.objects.values_list('title', flat=True).get(id=page[2:])
            elif page.startswith('s:'):
                return _('Editorial for %s') % Problem.objects.values_list('name', flat=True).get(code=page[2:])
            return '<unknown>'
        except ObjectDoesNotExist:
            return '<deleted>'

    @cached_property
    def page_title(self):
        return self.get_page_title(self.page)

    def is_accessible_by(self, user):
        try:
            if self.page.startswith('p:'):
                return Problem.objects.get(code=self.page[2:]).is_accessible_by(user)
            elif self.page.startswith('s:'):
                return Solution.objects.get(problem__code=self.page[2:]).is_accessible_by(user)
            elif self.page.startswith('b:'):
                return BlogPost.objects.get(id=self.page[2:]).can_see(user)
            else:
                return True
        except ObjectDoesNotExist:
            return False

    def get_absolute_url(self):
        return '%s#comment-%d' % (self.link, self.id)

    def __str__(self):
        return '%(page)s by %(user)s' % {'page': self.page, 'user': self.author.user.username}


class CommentVote(models.Model):
    voter = models.ForeignKey(Profile, related_name='voted_comments', on_delete=CASCADE)
    comment = models.ForeignKey(Comment, related_name='votes', on_delete=CASCADE)
    score = models.IntegerField()

    class Meta:
        unique_together = ['voter', 'comment']
        verbose_name = _('comment vote')
        verbose_name_plural = _('comment votes')


class CommentLock(models.Model):
    page = models.CharField(max_length=30, verbose_name=_('associated page'), db_index=True,
                            validators=[comment_validator])

    class Meta:
        permissions = (
            ('override_comment_lock', _('Override comment lock')),
        )

    def __str__(self):
        return str(self.page)

templates/comments/content.html
{{ comment.body|markdown('comment')|reference|str|safe }}

templates/comments/edit-ajax.html
<div class="ui container">
    <div class="ui segment">
        <form id="comment-edit" action="{{ request.get_full_path() }}" method="post" class="ui reply form">
            <span style="display: none" class="comment-id">{{ comment.id }}</span>
            <span style="display: none" class="read-back">{{ url('comment_content', comment.id) }}</span>
            {% csrf_token %}
            {% if form.non_field_errors() or form.body.errors %}
                <div class="form-errors">
                    {{ form.non_field_errors() }}
                    {{ form.body.errors }}
                </div>
            {% endif %}
            <div class="field">
                {{ form.body }}
            </div>
            <button type="submit" class="ui blue labeled submit icon button">
                <i class="edit icon"></i>
                <div class="content">
                    Edit comment
                </div>
            </button>
        </form>
    </div>
</div>

templates/comments/edit.html
{% extends "base.html" %}
{% block media %}
    {% compress css %}
        {{ form.media.css }}
    {% endcompress %}
{% endblock %}

{% block js_media %}
    {{ form.media.js }}
{% endblock %}
{% block body %}
    <div class="form-area">{% include "comments/edit-ajax.html" %}</div>
{% endblock %}

templates/comments/list.html
<div class="!max-w-none">
    <div class="flex items-center w-full py-2 text-3xl font-bold border-b border-slate-600">
        <i class="comments icon"></i>
        {{ _('Comments') }}
    </div>
    {% if has_comments %}
        {% set logged_in = request.user.is_authenticated %}
        {% set profile = request.user if logged_in else None %}
        {% for node in mptt_tree(comment_list) recursive %}
            <div id="comment-{{ node.id }}" data-revision="{{ node.revisions - 1 }}"
                data-max-revision="{{ node.revisions - 1 }}"
                data-revision-ajax="{{ url('comment_revision_ajax', node.id) }}" class="comment {% if node.score <= vote_hide_threshold %} bad-comment{% endif %}">
                {% with author=node.author %}
                <a href="{{ url('user_page', author.username) }}" class="block float-left w-10 h-auto mt-1 ml-4 mr-10">
                    <img src="{{ gravatar(author, 135) }}">
                </a>
                {% endwith %}
                <div class="flex flex-col">
                    <div class="flex items-center gap-4 metadata">
                        {{ link_user(node.author) }}
                        <div class="text-sm date text-slate-400">
                            {{ relative_time(node.time, abs=_('commented on {time}'), rel=_('commented {time}')) }}
                        </div>
                        <div class="rating">
                            {% if logged_in %}
                            <a href="javascript:comment_upvote({{ node.id }})" class="{% if node.vote_score == 1 %}text-green-50 {% else %} text-green-500 {% endif %}">
                                <i class="-rotate-90 upvote-link fa-solid fa-play "></i>
                            </a>
                            {% else %}
                            <a href="javascript:alert('{{ _('Please login to vote')|escapejs }}')" title="{{ _('Please login to vote') }}" class="text-green-500">
                                <i class="-rotate-90 upvote-link fa-solid fa-play"></i>
                            </a>
                            {% endif %}
                            <span class="comment-score">{{ node.score }}</span>
                            {% if logged_in %}
                            <a href="javascript:comment_downvote({{ node.id }})" class="{% if node.vote_score == -1 %} text-red-50 {% else %} text-red-500 {% endif %}">
                                <i class="rotate-90 downvote-link fa-solid fa-play"></i>
                            </a>
                            {% else %}
                            <a href="javascript:alert('{{ _('Please login to vote')|escapejs }}')" title="{{ _('Please login to vote') }}" class="text-red-500">
                                <i class="rotate-90 downvote-link fa-solid fa-play"></i>
                            </a>
                            {% endif %}
                        </div>
                        <div class="comment-edits">
                            {% if node.revisions > 1 %}
                            <span class="comment-edits">
                                <a href="javascript:show_revision({{ node.id }}, -1)" class="previous-revision">
                                    <i class="fa-solid fa-left-long"></i>
                                </a>
                                <span class="comment-edit-text">
                                    {% if node.revisions > 2 %}
                                        {% trans edits=node.revisions - 1 %}edit {{ edits }}{% endtrans %}
                                    {% else %}
                                        {{ _('edited') }}
                                    {% endif %}
                                </span>
                                <a href="javascript:show_revision({{ node.id }}, 1)" style="visibility: hidden" class="next-revision">
                                    <i class="fa-solid fa-right-long"></i>
                                </a>
                            </span>
                            {% else %}
                                <span class="comment-edits"></span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="mt-1 mb-2 text">
                        <div class="comment-body" {% if node.score <= vote_hide_threshold %} style="display:none"{% endif %}>
                            {{ node.body|markdown('comment', True)|reference|str|safe }}
                        </div>
                        {% if node.score <= vote_hide_threshold %}
                            <div class="bad-comment-body">
                                <p>
                                    {%- trans id=node.id -%}
                                        This comment is hidden due to too much negative feedback.
                                        Click <a href="javascript:comment_show_content({{ id }})">here</a> to view it.
                                    {%- endtrans -%}
                                </p>
                            </div>
                        {% endif %}
                    </div>
                    <div class="flex gap-2.5 text-sm actions">
                        <a href="#comment-{{ node.id }}" title="{{ _('Link') }}" class="comment-link">
                            <i class="fa-solid fa-link"></i>
                        </a>
                        {% if logged_in and not comment_lock %}
                        {% set can_edit = node.author.id == profile.id and not profile.mute %}
                        {% if can_edit %}
                        <a data-featherlight="{{ url('comment_edit_ajax', node.id) }}"
                            href="{{ url('comment_edit', node.id) }}"
                            title="{{ _('Edit') }}" class="edit-link">
                            <i class="fa-solid fa-pencil"></i>
                        </a>
                        {% else %}
                        <a href="javascript:reply_comment({{ node.id }})"
                            title="{{ _('Reply') }}">
                            <i class="fa-solid fa-reply"></i>
                        </a>
                        {% endif %}
                        {% if perms.judge.change_comment %}
                            {% if can_edit %}
                                <a href="javascript:reply_comment({{ node.id }})"
                                    title="{{ _('Reply') }}"><i class="fa-solid fa-reply"></i></a>
                            {% else %}
                                <a data-featherlight="{{ url('comment_edit_ajax', node.id) }}"
                                    href="{{ url('comment_edit', node.id) }}" title="{{ _('Edit') }}"
                                    class="edit-link"><i class="fa-solid fa-pencil"></i></a>
                            {% endif %}
                            <a data-featherlight="{{ url('comment_votes_ajax', node.id) }}"
                                href="javascript:void(0)"
                                title="{{ _('Votes') }}" class="votes-link"><i class="fa-solid fa-chart-column"></i></a>
                            <a href="javascript:void(0)" title="{{ _('Hide') }}" data-id="{{ node.id }}"
                                class="hide-comment"><i class="fa-solid fa-trash"></i></a>
                            <a href="{{ url('admin:judge_comment_change', node.id) }}"
                                title="{{ _('Admin') }}"><i class="fa-solid fa-gear"></i></a>
                        {% endif %}
                        {% endif %}
                    </div>
                    <div class="header-comment ui top attached secondary black inverted menu" style="display:none" id="header-{{ node.id }}-reply">
                        <h3 class="ui item header">{{ _('Replying to comment') }}</h3>
                        <div class="right menu"></div>
                    </div>
                    <div id="comment-{{ node.id }}-reply" class="reply-comment bottom attached ui segment" hidden></div>
                </div>
                {% with children=node.get_children() %}
                    {% if children %}
                        <div id="comment-{{ node.id }}-children" class="comments">{{ loop(children) }}</div>
                    {% endif %}
                {% endwith %}
            </div>
        {% endfor %}
    {% elif not comment_lock %}
        <p class="mt-2 text-lg font-normal text-black">{{ _('There are no comments at the moment.') }}</p>
    {% endif %}

    {% if request.user.is_authenticated and comment_form and not comment_lock %}
    <div class="flex flex-col p-2 mt-4 space-y-4 rounded-md shadow-md">
        {% block comment_submit_title %}
        <div class="flex p-4 -m-2 text-white bg-black rounded-t-md">
            <div class="flex-1 text-2xl font-bold">{{ _('New comment') }}</div>
            <div class="right menu"></div>
        </div>
        {% endblock %}
        <div class="flex flex-col">
            {% if is_new_user %}
                <div style="margin-bottom: 0" class="alert alert-info">
                    {{ _('You need to have solved at least one problem before your voice can be heard.') }}
                </div>
            {% else %}
                <form class="ui form" action="" method="post" id="new-comment">
                    {% csrf_token %}
                    {% if comment_form.errors %}
                        <div id="form-errors">
                            {{ comment_form.non_field_errors() }}
                            {{ comment_form.parent.errors }}
                            {% if comment_form.body.errors %}{{ _('Invalid comment body.') }}{% endif %}
                        </div>
                    {% endif %}
                    <div class="field">
                        {{ comment_form.parent }}
                        {{ comment_form.body }}
                    </div>
                    <button id="submit" type="submit" class="flex items-center px-4 py-2 font-semibold text-white bg-blue-500 rounded-md">
                        <i class="edit icon"></i>
                        <div class="content">
                            {{ _('Add comment') }}
                        </div>
                    </button>
                </form>
            {% endif %}
        </div>
        {% endif %}
    
        {% if comment_lock %}
            <div class="alert alert-warning comment-lock">
                {{ _('Comments are disabled on this page.') }}
            </div>
        {% endif %}
    </div>
</div>

templates/comments/math.html
{% compress js, inline %}
    <script src="{{ static('pagedown_math.js') }}?v=432"></script>
{% endcompress %}

templates/comments/preview.html
{{ preview_data|markdown('comment')|reference|str|safe }}
{% if REQUIRE_JAX %}
    <div data-config="{{ static('mathjax_config.js') }}" class="require-mathjax-support"></div>
{% endif %}

templates/comments/revision-ajax.html
{% with node=revision.field_dict %}
    <div class="comment-body">{{ node.body|markdown('comment')|reference|str|safe }}</div>
{% endwith %}

templates/comments/votes.html
<h2 style="text-align: center">{{ _('Votes') }}</h2>
<table class="table" style="display: table">
    <thead>
    <tr>
        <th>{{ _('Voter') }}</th>
        <th>{{ _('Score') }}</th>
    </tr>
    </thead>
    <tbody>
    {% for vote in votes %}
        <tr>
            <td>{{ link_user(vote.voter) }}</td>
            <td>{{ vote.score }}</td>
        </tr>
    {% else %}
        <tr>
            <td colspan="2">{{ _('No votes') }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>